behaviors:
  MarioBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      use_recurrent: true
      sequence_length: 64
      memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # gail: 
      #   strength: 0.1
      #   gamma: 0.99
      #   demo_path: Assets/Demonstrations/demonstrations_buena.demo
      #   use_actions: false
      #   use_vail: false
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000

  Generator:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 200000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000


environment_parameters:
  stage:
    curriculum:
      - name:  Stage0
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 3
          threshold: 95.0
          require_reset: true
        value: 0
      - name: Stage1
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 5
          threshold: 95.0
          require_reset: true
        value: 1