behaviors:
  MarioBehaviour:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 10000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 8
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000

  Generator:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 200000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000


environment_parameters:
  mario_learning:
    curriculum:
      - name: NoHoles # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 5
          threshold: 95.0
        value: 0
      - name:  OneHole # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 95.0
          require_reset: true
        value: 1
      - name: TwoHoles
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 95.0
          require_reset: true
        value: 2
      - name: ThreeHoles
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 95.0
          require_reset: true
        value: 2