behaviors:
  MarioBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      #use_recurrent: true
      #sequence_length: 64
      #memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail: 
        strength: 0.35
        gamma: 0.99
        demo_path: Assets/Demonstrations/demoman_22.demo
        #use_actions: false
        #use_vail: false
    behavioral_cloning:
      strength: 0.5
      demo_path: Assets/Demonstrations/demoman_22.demo
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000

  Generator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      use_recurrent: true
      sequence_length: 43
      memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000


environment_parameters:
  # generator_stage:
  #   curriculum:
  #     - name:  Stage0
  #       completion_criteria:
  #         measure: reward
  #         behavior: Generator
  #         signal_smoothing: true
  #         min_lesson_length: 3
  #         threshold: 95.0
  #         require_reset: true
  #       value: 0
  #     - name: Stage1
  #       completion_criteria:
  #         measure: reward
  #         behavior: Generator
  #         signal_smoothing: true
  #         min_lesson_length: 10
  #         threshold: 150.0
  #         require_reset: true
  #       value: 1
  stage:
    curriculum:
      - name:  Stage0
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 3
          threshold: 95.0
          require_reset: true
        value: 0
      - name: Stage1
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 150.0
          require_reset: true
        value: 1
      - name: Stage2
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 95.0
          require_reset: true
        value: 2
      - name: Stage3
        completion_criteria:
          measure: reward
          behavior: MarioBehaviour
          signal_smoothing: true
          min_lesson_length: 10
          threshold: 95.0
          require_reset: true
        value: 3